services:
  - type: web
    name: mlops-summative-ui
    runtime: docker
    dockerfilePath: ./Dockerfile
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: MODEL_PATH
        value: models/plant_disease_model.h5
      - key: DATA_DIR
        value: data/train
